HairSalon/Models/Client.cs
namespace HairSalon.Models
{
    public class Client
    {
        public int ClientId { get; set; }
        public string Name { get; set; }
        public int StylistId { get; set; }
        public virtual Stylist Stylist { get; set; }
    }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
    public class Stylist
    {
        public int StylistId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Client> Clients { get; set; }

        public Stylist()
        {
            this.Clients = new HashSet<Client>();
        }
    }
}

HairSalon/Models/eauContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public DbSet<Client> Clients { get; set; }
        public virtual DbSet<Stylist> Stylists { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }
    }
}

HairSalon/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly HairSalonContext _db;


        public ClientsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Client> model = _db.Clients.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Client client)
        {
            _db.Clients.Add(client);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            return View(thisClient);
        }
        public ActionResult Edit(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            return View(thisClient);

        }

        [HttpPost]
        public ActionResult Edit(Client client)
        {
            _db.Entry(client).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly HairSalonContext _db;

        public ClientsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Client client)
        {
            _db.Clients.Add(client);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            return View(thisClient);
        }
        public ActionResult Edit(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
            return View(thisClient);
        }

        [HttpPost]
        public ActionResult Edit(Client client)
        {
            _db.Entry(client).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Models
{
    public class HomeController: Controller
    {
        [HttpGet("/")]

        public ActionResult Index()
        {
            return View();
        }
    }
}

HairSalon/Controllers/StylistController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class StylistsController : Controller
    {
        private readonly HairSalonContext _db;


        public StylistsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Stylist stylist)
        {
            _db.Stylists.Add(stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Stylist thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.stylistId == id);
            return View(thisStylist);
        }
        public ActionResult Edit(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.stylistId == id);
            return View(thisStylist);

        }

        [HttpPost]
        public ActionResult Edit(Stylist stylist)
        {
            _db.Entry(stylist).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

HairSalon/Controllers/StylistsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class StylistsController : Controller
    {
        private readonly HairSalonContext _db;

        public StylistsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            ViewBag.ClientName = _db.Clients;
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Stylist stylist)
        {
            _db.Stylists.Add(stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Stylist thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
            ViewBag.thisStylistsClients = _db.Clients.Where(client => client.StylistId == id);
           
            return View(thisStylist);
        }

        public ActionResult Edit(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(stylists => stylists.StylistId == id);
            return View(thisStylist);
        }

        [HttpPost]

        public ActionResult Edit(Stylist stylist)
        {
            _db.Entry(stylist).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Add a new Client</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.LabelFor(model => model.StylistId)
    @Html.DropDownList("StylistId")

    <input type="submit" value="add a new client" class ="btn btn-default" />

   
}


<p>@Html.ActionLink("Show all Clients", "Index")</p>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>



<p>@Html.ActionLink("Back to List", "Index")</p>
<p>@Html.ActionLink("Edit Client", "Edit", new {id = Model.ClientId})</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h3>edit the list: @Html.DisplayFor(model => model.Name)</h3>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.LabelFor(model => model.Name)
     @Html.EditorFor(model => model.Name)

     @Html.LabelFor(model => model.Stylist)<br>
    @Html.DropDownList("StylistId")<br>

   
     <input type ="submit" value ="Save" />

}

<p> @Html.ActionLink("Back to List", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

    <h1>Restaurants</h1>

    @if (@Model.Count == 0)
    {
        <h3>No Clients have been added yet</h3>
    }

    <ul>@foreach(Client client in Model)
        {
             <li class="btn btn-info">@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId}) | @client.Stylist.Name</li>
        }
    </ul>

<p> @Html.ActionLink("Add new Client", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Home/index.cshtml
@{
    Layout ="_Layout";

}

<h1> Welcome to Eau-Clair's Salon</h1>
<p>@Html.ActionLink("See all Stylists", "Index", "Stylists")</p>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
    <title>Hair Salon</title>
</head>
<body>
    @RenderBody()
</body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a Stylist</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value ="Add a new stylist" class= "btn btn-default" />

}
<p> @Html.ActionLink("Show Stylist", "Index")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2> Stylist details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
   @foreach (var client in ViewBag.thisStylistsClients)
{
  <p>@client.Name</p>
}
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Stylist", "Edit", new {id= Model.StylistId})</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}
@model HairSalon.Models.Stylist
<h2>Edit the List</h2>
<h4>Edit this Stylist @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StylistId)
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type= "submit" value="Save" class = "btn btn-Default" />
}

<p> @Html.ActionLink("Back to List...","Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

    <h2>List of Stylist</h2>
    @if(Model.Count== 0)
    {
        <h3> No Stylists have been added yet!!</h3>
    }

    <ul>
        @foreach (Stylist stylist in Model)
        {
            <li>
                @Html.ActionLink($"{stylist.Name}","Details", new { id = stylist.StylistId})
            </li>
        }
    </ul>
    <p>@Html.ActionLink("Add new Stylist", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("List of Stylist", "Index", "Stylists")</p>
<div class ="card-footer">
 <a class="btn btn-outline-info" href="/Clients/Create">Add clients</a>
  <a class="btn btn-outline-light" href="/Clients">View clients</a>
  </div>